export default {
  user: {
    user_id: 1,
    isLoggedIn: false,
    location: null,

    // profile: {
    //   avatar: 'https://i.ytimg.com/vi/1v6M41Divso/maxresdefault.jpg',
    //   name: 'Kim Panda',
    //   address: 'back handle lane Austin, VA',
    //   zip: '56352',
    // },
    isDriver: false,
    isRider: false,
    isFetchingUserState: false,
    isChangingAddress: false,
    changeAddressError: false,
    requestUserError: false,
    friends: [],
    addedFriend: null,
  },
  ride: {
    ride_id: 3,
    match: null,
    matchFlag: false,
    directions: null,
    riders: [],
    messages: [
      { user_id: 9, time: '12:30', text: 'Where are you?', },
      { user_id: 8, time: '12:42', text: 'On my way. Where you at?', },
      { user_id: 9, time: '12:45', text: 'Four Horseman', },
      { user_id: 8, time: '12:50', text: 'Be there in ten.', },
    ],
    isWaitingForMatch: false,
    isAddingDriver: false,
    isRemovingDriver: false,
    isMatched: false,
    isConfirmed: false,
    isCancelling: false,
    isAccepting: false,
    isFetchingMessages: false,
    isPickedUp: false,
    acceptRideError: null,
    rideRequestError: null,
    messagesFetchError: null,
    driverAddError: null,
  },
  routing: {
    locationBeforeTransitions: null,
  },
};
